In [1]:
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import print_function

import sys
from random import random
from operator import add
import os
import sys
from pyspark.sql import SparkSession


spark = SparkSession\
    .builder\
    .appName("PythonPi")\
    .getOrCreate()

print("\n\n\n\n\n ----------------- MY CODE EXECUTION ------------------- \n\n\n\n\n")
    
# Now I will be testing and modifying the above code to enable it for all use cases
from mosaicml import expai
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
from mosaicml import *
from mosaicml.constants import MLModelFlavours
import numpy as np

iris = datasets.load_iris()
X = iris.data
y = iris.target

import sklearn
from sklearn.model_selection import train_test_split
import numpy as np
import time

X_train,X_test,Y_train,Y_test = train_test_split(X,y, test_size=0.2, random_state=0)

clf = RandomForestClassifier(random_state=0, n_jobs=-1)
clf = clf.fit(X_train, Y_train)

@scoring_func
def score(model, request):
    payload = request.json["payload"]
    data_list = payload
    data_array = np.asarray(data_list)
    try:
        prediction = model.predict(data_array)
    except:
        prediction = model.predict(data_array.reshape(1, -1))
    return prediction.tolist()

# # to verify if score func works
import requests
req = requests.Request()
req.json = {"payload":X_train[100]}

print(score(clf,req))

Y_true = Y_test
Y_pred = clf.predict(X_test)

prob1=clf.predict_proba(X_test)

register_model(
    clf,
    score,
    "iris_classfication_2",
    "iris_classfication_2",
    MLModelFlavours.sklearn,
    init_script="mkdir abc \\n cd abc \\n touch abc.txt",
    input_type="json",
    original_features=iris.feature_names,
    y_true=Y_true,
    y_pred=Y_pred,
    prob=prob1,
    model_type = "classification",
    explain_ai=True,
    x_train=X_train, 
    y_train=Y_train, 
    feature_names=iris.feature_names,
    features=iris.feature_names, 
    feature_ids=iris.feature_names,
    target_names=iris.target_names.tolist(),
    mode="classification"
)
print("\n\n\n\n\n ----------------- Done ------------------- \n\n\n\n\n")

spark.stop()


[2]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[[0.  0.  1. ]
 [0.  0.9 0.1]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.6 0.4]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.1 0.9]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.1 0.9]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]]
[0.  0.9 0.  0.  0.  0.  0.  1.  1.  1.  0.6 1.  1.  1.  1.  0.  1.  1.
 0.  0.  0.1 1.  0.  0.  0.1 0.  0.  1.  1.  0. ]


Calculating build time metrics

Progress: ██████████████████████████████████████████████████████████████████████ 100.0%


2020-12-11 10:29:59,148 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-12-11 10:29:59,152 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[25/25] grid cells ████████████████████ Time elapsed: 8 seconds

2020-12-11 10:30:09,448 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-12-11 10:30:09,452 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[22/22] grid cells ████████████████████ Time elapsed: 7 seconds

2020-12-11 10:30:18,443 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-12-11 10:30:18,448 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[25/25] grid cells ████████████████████ Time elapsed: 8 seconds

2020-12-11 10:30:28,547 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progressbar=False
2020-12-11 10:30:28,644 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[22/22] grid cells ████████████████████ Time elapsed: 7 seconds

2020-12-11 10:30:38,338 - skater.core.explanations - WARNING - Progress bars slow down runs by 10-20%. For slightly 
faster runs, do progress_bar=False
2020-12-11 10:30:38,342 - skater.core.explanations - WARNING - Multiprocessing failed, going single process


[4/4] features ████████████████████ Time elapsed: 2 seconds

2020-12-11 10:30:41,363 - skater.core.global_interpretation.tree_surrogate - INFO - post pruning applied ...
2020-12-11 10:30:41,368 - skater.core.global_interpretation.tree_surrogate - INFO - Scorer used cross-entropy
2020-12-11 10:30:41,443 - skater.core.global_interpretation.tree_surrogate - INFO - original score using base model 2.1094237467877998e-15
2020-12-11 10:30:41,548 - skater.core.global_interpretation.tree_surrogate - INFO - Summary: childrens of the following nodes are removed []
2020-12-11 10:30:41,550 - skater.core.global_interpretation.tree_surrogate - INFO - Done generating prediction using the surrogate, shape (120, 3)
2020-12-11 10:30:41,553 - skater.core.global_interpretation.tree_surrogate - INFO - Done scoring, surrogate score 0.0; oracle score 0.034
2020-12-11 10:30:41,645 - skater.core.global_interpretation.tree_surrogate - WARNING - impurity score: 0.034 of the surrogate model is higher than the impurity threshold: 0.01. The higher the impurity score, lower is

{'created_by': 'devesh.surve@lntinfotech.com',
 'created_on': '2020-12-11T10:29:50+00:00',
 'deploymentstatus': False,
 'description': 'iris_classfication_2',
 'flavour': 'sklearn',
 'id': 'a6cd528b-ee51-4d86-a9a0-7762fed7fc9c',
 'last_modified_by': 'devesh.surve@lntinfotech.com',
 'last_modified_on': '2020-12-11T10:29:50+00:00',
 'model_display': True,
 'name': 'iris_classfication_2',
 'project_id': '8036c7bd-4d5f-478e-a3a1-8fda0d715aee',
 'source': '',
 'tags': None,
 'type': 'model',
 'versions': [{'created_by': 'devesh.surve@lntinfotech.com',
   'created_on': '2020-12-11T10:29:50+00:00',
   'datasource_name': '',
   'dependent_model': None,
   'deploy_info': None,
   'deployments': [],
   'description': None,
   'docker_image_url': 'registry.lti-aiq.in:443/mosaic-ai-logistics/mosaic-ai-serving:1.0.0-07122020',
   'gpu_docker_image_url': 'registry.lti-aiq.in:443/mosaic-ai-logistics/mosaic-ai-serving:gpu-1.0.0-07122020',
   'id': '0d0e5ed3-6c15-4dbd-8aff-de7690cef48a',
   'init_scrip