In [1]:
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

from __future__ import print_function

import sys
from random import random
from operator import add
import os
import sys
from pyspark.sql import SparkSession


spark = SparkSession\
    .builder\
    .appName("PythonPi")\
    .getOrCreate()

print("\n\n\n\n\n ----------------- MY CODE EXECUTION ------------------- \n\n\n\n\n")
    
# Now I will be testing and modifying the above code to enable it for all use cases
from sklearn.ensemble import RandomForestClassifier
from sklearn import datasets
import numpy as np

iris = datasets.load_iris()
X = iris.data
y = iris.target
print("iris data loaded")
print(X[:5]"\n")
import sklearn
from sklearn.model_selection import train_test_split
import numpy as np
import time

X_train,X_test,Y_train,Y_test = train_test_split(X,y, test_size=0.2, random_state=0)
print("iris data split")
print(X_train[:5]"\n")

clf = RandomForestClassifier(random_state=0, n_jobs=-1)
clf = clf.fit(X_train, Y_train)
print("iris model trained ",clf)

def score(model, request):
    payload = request.json["payload"]
    data_list = payload
    data_array = np.asarray(data_list)
    try:
        prediction = model.predict(data_array)
    except:
        prediction = model.predict(data_array.reshape(1, -1))
    return prediction.tolist()

# # to verify if score func works
import requests
req = requests.Request()
req.json = {"payload":X_train[100]}
print("iris model request and score ",req.json)
print("prediction",score(clf,req))

Y_true = Y_test
Y_pred = clf.predict(X_test)

prob=clf.predict_proba(X_test)

print("\n\n\n\n\n ----------------- Done ------------------- \n\n\n\n\n")

spark.stop()


[2]
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[2 1 0 2 0 2 0 1 1 1 1 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
[[0.  0.  1. ]
 [0.  0.9 0.1]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  0.  1. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  0.6 0.4]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.1 0.9]
 [0.  1.  0. ]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  0.1 0.9]
 [1.  0.  0. ]
 [1.  0.  0. ]
 [0.  1.  0. ]
 [0.  1.  0. ]
 [1.  0.  0. ]]
[0.  0.9 0.  0.  0.  0.  0.  1.  1.  1.  0.6 1.  1.  1.  1.  0.  1.  1.
 0.  0.  0.1 1.  0.  0.  0.1 0.  0.  1.  1.  0. ]
